import React from 'react';
import Head from 'next/head';
import Link from 'next/link';
import api from 'services/restapi';
import { Col, Container, Form, Row, Card } from 'react-bootstrap';
import MailIcon from '@material-ui/icons/Mail';
import AddIcCallIcon from '@material-ui/icons/AddIcCall';
import PermIdentityIcon from '@material-ui/icons/PermIdentity';
import FaceIcon from '@material-ui/icons/Face';
import LockIcon from '@material-ui/icons/Lock';

function signUp() {
    const [disable, setDisable] = React.useState(false)
    const [user, setUser] = React.useState({
        first_name: '',
        last_name: '',
        email: '',
        username: '',
        no_telp: '',
        password: '',
        repassword: '',
    })
    const handleSubmit = async (e) => {
        e.preventDefault()
        const { data: regist } = await api.post('auth/do-regist', user)
        console.log(regist);
    }
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="page-header position-relative page-bg">
                <Container style={{zIndex: "2"}}>
                    <Row>
                        <Col className="mx-auto" lg="4" md="4">
                            <Card className="card-login ">
                                <Form onSubmit={handleSubmit} className="form" noValidate>
                                    <Card.Header className="card-header-primary text-center">
                                        <Card.Title>
                                            <h4>Register</h4>
                                        </Card.Title>
                                        <Card.Subtitle>
                                            Auth system Palads Futsal
                                        </Card.Subtitle>
                                    </Card.Header>
                                    <Card.Body>
                                        <span className="bmd-form-group is-focused">
                                            <div className="input-group">
                                                <div className="input-group-prepend">
                                                    <span className="input-group-text">
                                                        <PermIdentityIcon></PermIdentityIcon>
                                                    </span>
                                                </div>
                                                <input name="first_name" type="text" onChange={(e) => setUser({...user, first_name: e.target.value})} className="form-control" placeholder="Your First Name..." required/>
                                            </div>
                                        </span>
                                        <span className="bmd-form-group is-focused">
                                            <div className="input-group">
                                                <div className="input-group-prepend">
                                                    <span className="input-group-text">
                                                        <PermIdentityIcon></PermIdentityIcon>
                                                    </span>
                                                </div>
                                                <input name="last_name" type="text" onChange={(e) => setUser({...user, last_name: e.target.value})} className="form-control" placeholder="Your Last Name..." required/>
                                            </div>
                                        </span>
                                        <span className="bmd-form-group is-focused">
                                            <div className="input-group">
                                                <div className="input-group-prepend">
                                                    <span className="input-group-text">
                                                        <MailIcon></MailIcon>
                                                    </span>
                                                </div>
                                                <input name="email" type="email" onChange={(e) => setUser({...user, email: e.target.value})} className="form-control" placeholder="Email..." required/>
                                            </div>
                                        </span>
                                        <span className="bmd-form-group is-focused">
                                            <div className="input-group">
                                                <div className="input-group-prepend">
                                                    <span className="input-group-text">
                                                        <FaceIcon></FaceIcon>
                                                    </span>
                                                </div>
                                                <input name="username" type="text" onChange={(e) => setUser({...user, username: e.target.value})} className="form-control" placeholder="Username..." required/>
                                            </div>
                                        </span>
                                        <span className="bmd-form-group is-focused">
                                            <div className="input-group">
                                                <div className="input-group-prepend">
                                                    <span className="input-group-text">
                                                        <AddIcCallIcon></AddIcCallIcon>
                                                    </span>
                                                </div>
                                                <input name="no_telp" type="telp" onChange={(e) => setUser({...user, no_telp: e.target.value})} className="form-control" placeholder="0811111111"/>
                                            </div>
                                        </span>
                                        <span className="bmd-form-group is-focused">
                                            <div className="input-group">
                                                <div className="input-group-prepend">
                                                    <span className="input-group-text">
                                                        <LockIcon></LockIcon>
                                                    </span>
                                                </div>
                                                <input name="password" type="password" onChange={(e) => setUser({...user, password: e.target.value})} className="form-control" placeholder="Password..."/>
                                            </div>
                                        </span>
                                        <span className="bmd-form-group is-focused">
                                            <div className="input-group">
                                                <div className="input-group-prepend">
                                                    <span className="input-group-text">
                                                        <LockIcon></LockIcon>
                                                    </span>
                                                </div>
                                                <input name="repassword" type="password" onChange={(e) => setUser({...user, repassword: e.target.value})} className="form-control" placeholder="Re-Password..."/>
                                            </div>
                                        </span>
                                    </Card.Body>
                                    <div className="footer-auth text-center">
                                        <button type="submit" className="btn btn-primary btn-link btn-wd btn-lg" disabled={disable}>Submit</button>
                                    </div>
                                </Form>
                            </Card>
                        </Col>
                    </Row>
                    <Row>
                        <Col className="text-center">
                            <span className="text-white">
                                Having account ?
                            </span>{' '}
                            <Link href="/sign-in">Login</Link>
                        </Col>
                    </Row>
                </Container>
            </div>
        </>
    )
}

export default signUp;