import React from 'react';
import { useRouter } from 'next/router';
import Head from 'next/head';
import Link from 'next/link';
import { Col, Container, Form, Row, Card } from 'react-bootstrap';
import FacebookIcon from '@material-ui/icons/Facebook';
import InstagramIcon from '@material-ui/icons/Instagram';
import TwitterIcon from '@material-ui/icons/Twitter';
import FaceIcon from '@material-ui/icons/Face';
import LockIcon from '@material-ui/icons/Lock';
import useAuth from '/helpers/Context';
import Cookies from 'js-cookie';

function signIn() {
    const router = useRouter()
    const {user, login} = useAuth()
    const [loading, setLoading] = React.useState(false)
    const [auth, setAuth] = React.useState({username: '', password: ''})

    const handleChange = e => {
        setAuth({...auth, [e.target.name]: e.target.value})
    }

    const handleSubmit = async (e) => {
        e.preventDefault()
        setLoading(true)
        if (auth.username === '' || auth.password === '') {
            alert('tidak boleh kosong')
        } else {
            const user = await login(auth.username, auth.password)
            setLoading(false)
            if (user) {
                const role = Cookies.get('role')
                if (role === 'member') {
                    router.push('/')
                } else {
                    router.push('/sign-up')
                }
            } else {
                alert('gagal bos!')
            }
        }
    }
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="page-header position-relative page-bg">
                <Container style={{zIndex: "2"}}>
                    <Row>
                        <Col className="mx-auto" lg="4" md="4">
                            <Card className="card-login">
                                <Form onSubmit={handleSubmit} className="form" noValidate>
                                    <Card.Header className="card-header-primary text-center">
                                        <Card.Title>
                                            <h4>Login</h4>
                                        </Card.Title>
                                        <div className="social-line">
                                            <a href="#pablo" className="btn btn-just-icon btn-link">
                                                <FacebookIcon></FacebookIcon>
                                            </a>
                                            <a href="#pablo" className="btn btn-just-icon btn-link">
                                                <InstagramIcon></InstagramIcon>
                                            </a>
                                            <a href="#pablo" className="btn btn-just-icon btn-link">
                                                <TwitterIcon></TwitterIcon>
                                            </a>
                                        </div>
                                    </Card.Header>
                                    <p className="description text-center">Or Be Classical</p>
                                    <Card.Body>
                                        <span className="bmd-form-group is-focused">
                                            <div className="input-group">
                                                <div className="input-group-prepend">
                                                    <span className="input-group-text">
                                                        <FaceIcon></FaceIcon>
                                                    </span>
                                                </div>
                                                <input name="username" type="text" onChange={handleChange} className="form-control" placeholder="Username..." required/>
                                            </div>
                                        </span>
                                        <span className="bmd-form-group is-focused">
                                            <div className="input-group">
                                                <div className="input-group-prepend">
                                                    <span className="input-group-text">
                                                        <LockIcon></LockIcon>
                                                    </span>
                                                </div>
                                                <input name="password" type="password" onChange={handleChange} className="form-control" placeholder="Password..." required/>
                                            </div>
                                        </span>
                                    </Card.Body>
                                    <div className="footer-auth text-center">
                                        <button type="submit" className="btn btn-primary btn-link btn-wd btn-lg">Get Started</button>
                                    </div>
                                </Form>
                            </Card>
                        </Col>
                    </Row>
                    <Row>
                        <Col className="text-center">
                            <span className="text-white">
                                Don't have account ?
                            </span>{' '}
                            <Link href="/sign-up">Register</Link>
                        </Col>
                    </Row>
                </Container>
            </div>
        </>
    )
}

export default signIn
